### ISSUE TITLE
Bug: White Dots on the screen

### ISSUE THREAD

**Issue by exzenous** [michalleptuch/calendar-flyout#11]
There are dots, one in the middle and around right top of the screen, when I have Calendar Flyout opened. It's gone when I quit the app.
Is this something necessary for the app to work?
It's more like an eye sore to me and when I first see it, I thought I have a monitor problem.

![Screenshot 2023-01-25 130421](https://user-images.githubusercontent.com/33378035/214497193-fb2163a8-d9a1-43e8-916d-31c22b93cc97.png)

**Comment by michalleptuch** [comment]
Could you tell me what version of Windows 11 and version of my app are you using?

**Comment by exzenous** [comment]
Windows 11 Insider Dev build : 25281
Calendar Flyout: 1.9.3

**Comment by michalleptuch** [comment]
Okay, I need to install Insider build to check this issue.
Do you use apps that tweak UI? E.g.: StarDock, Rectify and so on?

**Comment by michalleptuch** [comment]
Currently I can't reproduce this bug

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/43097852/214653032-49e35cbf-8de2-4e79-8ed6-2654a12fc828.png">

**Comment by exzenous** [comment]
No, I don't.

**Comment by exzenous** [comment]
I just realize that I have Mica for Everyone. Which maybe the factor that causes the problem.
Right now the problem seems to be on and off to me. Sometimes I don't have the problem.

**Comment by michalleptuch** [comment]
Okay, just open Mica for Everyone, add new rule for CalendarFlyout.Wpf.exe and disable custom styles for this process.
