### ISSUE TITLE
Not available in Greece for purchase

### ISSUE THREAD

**Issue by psycho-bits** [michalleptuch/calendar-flyout#17]
Hi, great little app, 
I want to buy it but it is not available to the Windows Store from Greece. If i go through the web link to the store, I can see the app but no option to purchase is or download it and if i search for it in my store no results are returned.
Will be good if you can make it available to Greece or provide alternative channels to purchase it.
Thanks

**Comment by michalleptuch** [comment]
It's a temporary situation in all the countries. It may take a few days to get available again. Please be patient 🙂
