### ISSUE TITLE
Feature request: Widget

### ISSUE THREAD

**Issue by hypedcolee7881** [michalleptuch/calendar-flyout#18]
It would very useful if Calendar Flyout had a widget compatible with the widget board in Windows 11.

The widget board is now compatible with third party widgets.

Although the widget board has an Outlook Calendar widget, that one is only compatible with personal microsoft accounts; not exchange calendars or google calendar like Calendar Flyout.

**Comment by michalleptuch** [comment]
Widget board in Windows 11 has inferior performance and doesn't support all functions that I need. I decided to not implement widget for Calendar Flyout app for now.
