### ISSUE TITLE
Feature Request: Change Colour

### ISSUE THREAD

**Issue by AlanWade** [michalleptuch/calendar-flyout#19]
It would be nice if we could change the text colour. If I open the flyout over a white background the date is only just visible.

**Comment by AlanWade** [comment]
Sure mate

![2023-04-14_08-41-21](https://user-images.githubusercontent.com/45734370/231963678-077462d1-d9ca-45b7-b1f0-c08315259b0a.jpg)

**Comment by hypedcolee7881** [comment]
I think that color is actually governed by the 'accent color' you set in Windows Settings under Personalization > Colors. Try switching that up.

**Comment by AlanWade** [comment]
Yep that did it, thankyou for your help
