### ISSUE TITLE
Dark overlay bug

### ISSUE THREAD

**Issue by ashergz** [michalleptuch/calendar-flyout#2]
I'm facing this weird issue with Calendar Flyout. When executed, this small square box appears in the top left corner and when I click or right click the flyout system tray icon, the box gets bigger. Please see video for reference:

https://user-images.githubusercontent.com/35883201/181830787-2a491e06-0688-49ef-b5dc-4128387f1cff.mp4

Can you please look into this issue. Let me know if you need any more info.

**Comment by michalleptuch** [comment]
What software do you use for UI customizations?

**Comment by ashergz** [comment]
Uh... the date thing on the desktop is Rainmeter. There's also RoundedTB. Or do you mean something else?

**Comment by michalleptuch** [comment]
There is software on your PC that modifies all opened windows and other parts of the system (including dark mode). I can't reproduce this bug on my machines.

Btw... what is your Windows build number?

**Comment by ashergz** [comment]
Well I do use MicaForEveryone that modifies Window backgrounds, but even when I close that the overlay still appears

**Comment by ashergz** [comment]
Oh and I just updated to the latest dev build 25169.1000 The issue was there on previous builds as well.

**Comment by michalleptuch** [comment]
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/43097852/181845831-d75f192e-85bf-4b24-a26c-da3f81d1a801.png">

1. Open Mica for everyone settings
2. Add new rule for process **CalendarFlyout.Wpf**
3. Make sure all settings for this rule are the same as above
4. Restart Calendar Flyout

**Comment by ashergz** [comment]
Thanks, that worked like a charm!
