### ISSUE TITLE
Remove review request when it's already done?

### ISSUE THREAD

**Issue by AkazaRenn** [michalleptuch/calendar-flyout#24]
Hi, I'm getting the review request (yellow start button on top-right corner) in about every two weeks. It's a bit annoying because I have to click it and open the store then close the store, doing nothing, because I had reviewed on the first day installing the app... Is there any chance that we can actually detect whether the app has been reviewed in the store, and only put up the button when it's not?

Thank you!

**Comment by michalleptuch** [comment]
Hi, it'll be fixed in the next update. Thank you for your patience 🙏
