### ISSUE TITLE
Bug: Memory leak when you turn off all calendar accounts

### ISSUE THREAD

**Issue by HtheB** [michalleptuch/calendar-flyout#25]
I only have one calendar account by default inside the app. Whenever you turn that off, the CPU usage will go up very high and the app can't be used anymore. The taskbar icon flashes really fast as if it tries to open and close itself.

The only way to fix it, is to go to the Windows System settings > Apps > Installed Apps > Click on the 3 dots at Calendar Flyout > Advanced options > Reset

**Comment by michalleptuch** [comment]
Hello, what is the version of Calendar Flyout installed on your PC?

**Comment by HtheB** [comment]
Version: 1.9.8

**Comment by michalleptuch** [comment]
Will be fixed in 2.0.0.
