### ISSUE TITLE
Bug: calendar events not showing up as of v2.0.0

### ISSUE THREAD

**Issue by BearBearCodes** [michalleptuch/calendar-flyout#29]
Hi, I recently purchased your app and it was working well until the latest update a few days ago (v2.0.0). I am currently on v2.0.1.0 from the Microsoft store.

My events are not showing up on the calendar flyout (see screenshot below), despite having added my Google account for my Google calendar in the Calendar Flyout settings page.
![image](https://github.com/michalleptuch/calendar-flyout/assets/64443273/ba139c93-c7d3-439d-b7eb-667ac2cf9dfc)

I am still using the old Windows calendar, not the new Outlook calendar (see screenshot below). I've tried switching to the new Outlook calendar as well, but that does not fix the issue either.
<img width="872" alt="screenshot_redacted" src="https://github.com/michalleptuch/calendar-flyout/assets/64443273/0ca7f4de-a63e-4d67-b31f-4684e745f79d">

Thanks for the help and for bringing this core functionality back to Windows!

**Comment by michalleptuch** [comment]
Hi, there is no support for Google calendars because the app has been rewritten from the scratch using newer technologies. I apologize for this situation. I'll add support for Google calendars in the next updates.

Thank you for your patience 🙏

**Comment by BearBearCodes** [comment]
No worries. Thanks for the info, and looking forward to the next update :D

**Comment by SmoothDenis** [comment]
Calendars from Exchange also dont work after the update

**Comment by michalleptuch** [comment]
What error do you get when you want to add Exchange account?

**Comment by SmoothDenis** [comment]
@michalleptuch I have not found a way to log in to Exchange on a third-party server, it is possible to log in only through the official Microsoft website

**Comment by michalleptuch** [comment]
Even when you go to Calendar Flyout settings > Accounts > Add account and select Work or school account?

**Comment by SmoothDenis** [comment]
yes, it opens the official Microsoft website, which does not authorize on my Exchange server

Any other application with regular Exchange authorization is correct. For example, the new Outlook does not support Exchange authorization directly, but the old Windows mail application has this option and it still works

**Comment by michalleptuch** [comment]
Okay, please create separated issue for your case :)

**Comment by michalleptuch** [comment]
I'm waiting for Google to verify my application.

**Comment by BearBearCodes** [comment]
Apologies for the ping—is there an ETA for the fix? I haven't been able to use the calendar since February
