### ISSUE TITLE
outlook account always showing fix account

### ISSUE THREAD

**Issue by fredboulanger** [michalleptuch/calendar-flyout#30]
Hi I have two accounts one for work one perso, both MSFT acccounts. My perso account (Outlook) - keeps showing it needs fixing in the flyout and on the taskbar with a ! in a red circle.

**Comment by michalleptuch** [comment]
Please, contact me via email: Calendar Flyout > Settings > About > Email support

<img width="603" alt="image" src="https://github.com/michalleptuch/calendar-flyout/assets/43097852/c812b382-3765-44c9-adbd-52db53a1b189">
