### ISSUE TITLE
Some events don't show up on the correct day

### ISSUE THREAD

**Issue by anthonyg2003** [michalleptuch/calendar-flyout#31]
Using Calendar Flyout v 2.0.3 on Windows 11

I'm in (UTC-07:00) Mountain Time zone. When a day is selected, the calendar displays some events from the previous day. Clicking on the events correctly shows the event details, including the correct date/time, but they appear on the wrong day. I think it's a timezone issue with Calendar Flyout because it's only the meetings at the end of the day that show up on the next day. 

I did a test where I created events the prior day starting at 1p UTC-07:00 on Feb 9, and those events at 5p and later appeared on Feb 10:

![image](https://github.com/michalleptuch/calendar-flyout/assets/19936471/6046f93a-dbf5-45d7-89b2-9e9422058cff)

**Comment by michalleptuch** [comment]
Hello, thanks for reporting the issue. Yeah, I'm testing version 2.0.4 with a fix for that. Sorry for the problem.
