### ISSUE TITLE
Unable to add account in Windows 11

### ISSUE THREAD

**Issue by zeuski52** [michalleptuch/calendar-flyout#37]
Hi, I recently switched to Windows 11, whenever I try to add an account the spinning loading icon appears, then after a minute it stops but never prompts me to enter anything. Is there a solution for this?

**Comment by michalleptuch** [comment]
Please, contact me using email.
Right-click on Calendar Flyout icon in notification area > Settings > About > Email support.

**Comment by michalleptuch** [comment]
What were you testing with your calendars? Your description means nothing without any details about what you did ;)

**Comment by kamilp** [comment]
Hi, I was just trying to import my Google calendar to my MS account (which worked fine). 

And yes, I did see the window where I select either the MS account I'm logged into, or login to a new account. Tried both ways (but using the same MS account). The process went fine, my credentials were approved, the window closed -- and nothing. The loader icon spinned for a sec -- and no account was added. 

And no, I'm not using a VPN.

**Comment by tmpeh** [comment]
I have the exact same problem. First login worked fine. Then I logged out and tried to login again, but when I press next in the popup window it disappears and nothing happens. Reset and reinstall of the app does not help.

**Comment by michalleptuch** [comment]
> Hi, I was just trying to import my Google calendar to my MS account (which worked fine).
> 
> And yes, I did see the window where I select either the MS account I'm logged into, or login to a new account. Tried both ways (but using the same MS account). The process went fine, my credentials were approved, the window closed -- and nothing. The loader icon spinned for a sec -- and no account was added.
> 
> And no, I'm not using a VPN.

Did you follow this article?
https://support.microsoft.com/en-us/office/see-your-google-calendar-in-outlook-c1dab514-0ad4-4811-824a-7d02c5e77126#PickTab=New_Outlook

**Comment by tmpeh** [comment]
Yes, I actually have multiple calendars linked. I added some in between the login attempts.

**Comment by michalleptuch** [comment]
> Yes, I actually have multiple calendars linked. I added some in between the login attempts.  

Please, contact me using email.
Right-click on Calendar Flyout icon in notification area > Settings > About > Email support.
