### ISSUE TITLE
Wrong positioning/scaling after changing monitor

### ISSUE THREAD

**Issue by AkazaRenn** [michalleptuch/calendar-flyout#38]
Like in this screenshot where only a half of the window appears in the screen, I think it's caused by attaching and changing the main display to another monitor with a different DPI. Could you please consider fixing it? Thank you!

![Screenshot 2024-05-05 191510](https://github.com/michalleptuch/calendar-flyout/assets/8340896/79da2766-004b-4dd8-a41c-8c42d76775c5)

**Comment by michalleptuch** [comment]
Please, share more info like:
- your display resolution,
- your display scaling,
- numbers of displays/monitors,
- Windows version (Win + R > winver)

**Comment by AkazaRenn** [comment]
@michalleptuch 
Here's the display setup when this issue happened (on the right side of display 3)
![Screenshot 2024-05-24 221617](https://github.com/michalleptuch/calendar-flyout/assets/8340896/7ff5dbe1-a64b-443f-90cd-cf4e540d34d7)
Another condition is a single laptop display, 1920 x 1200, 200% scaling, I switch between these two setups

As of WinVer:
```
Edition          Windows 11 Pro
Version          23H2
Installed on     24/03/22
OS build         22631.3593
```

**Comment by michalleptuch** [comment]
@AkazaRenn, problem fixed but I'm still testing.
Fix will be included in the next update.
