### ISSUE TITLE
Calendar not syncing

### ISSUE THREAD

**Issue by searledan** [michalleptuch/calendar-flyout#40]
I am unsure how often the data is supposed to synchronise however, multiple times I am having to do the sync manually as the data is not being fetched.

I have made sure power settings don't interfere with the application running in the background etc.

Also, it would be good to have an option to choose how frequently I would like the calendars to sync.

**Comment by michalleptuch** [comment]
Please, contact me using email.
Right-click on Calendar Flyout icon in notification area > Settings > About > Email support.

**Comment by searledan** [comment]
I have emailed but not heard back. Just wanting to make sure you have recieved the email...

**Comment by michalleptuch** [comment]
Critical global failure related to synchronization process (WNS).

**Comment by michalleptuch** [comment]
Fixed in version 2.0.8. Please, update Calendar Flyout app.

**Comment by searledan** [comment]
This still seems to be an issue and the extra info around sync frequency/time would be helpful to make sure I am not being impatient.

**Comment by michalleptuch** [comment]
Yeah, there is another fix on the way (2.0.9). It should be available within three business days.

Syncing occurs every 30 minutes and there is no option to change the frequency. I will consider your proposal, but I don't plan to include this change in the next big update (2.1.0).

**Comment by michalleptuch** [comment]
I reopened this issue due to some problems on Microsoft end: https://github.com/MicrosoftDocs/windows-dev-docs/issues/5027
