### ISSUE TITLE
Microsoft store report 660mb of file size.

### ISSUE THREAD

**Issue by Wip-Sama** [michalleptuch/calendar-flyout#42]
This is more like a curiosity than anything else, why does Microsoft store say that this application is 663 MB?
This app does not feel like it should be 600+mb for what it does.
Also, 663 is just above the Virustotal upload max size of 650 MB, which does not add a lot of trust to the project since a lot of bad actors add garbage to the application to avoid the scan on Virustotal.

**Comment by michalleptuch** [comment]
Hello, the last update package size is around 160-180 MB. I don't know why Microsoft Store shows wrong size. It's not a bug of my app.
