### ISSUE TITLE
Time chooser in 24H format

### ISSUE THREAD

**Issue by GodlikeRU** [michalleptuch/calendar-flyout#45]
Hello,

I really like your app, however one thing is annoying me in it. The time chooser when planning a new event. Instead of normal 24H format, it uses that weird AM/PM thing. Could you please make it normal?

![image](https://github.com/user-attachments/assets/206e2f33-297e-40c2-903b-9f0af8f26871)

That would make adding events easier. Thanks!

**Comment by michalleptuch** [comment]
What are region and time format settings of your system?
What is the version of installed OS?

**Comment by GodlikeRU** [comment]
Hey Michał,

It's Windows 11 build 22631 - up to date.

Timezone is Poland/Warsaw. Windows language is English US, Regional settings are polish, location is Poland. 
![Clipboard Image (1)](https://github.com/user-attachments/assets/901189b6-aade-4f44-a54e-fa4ae891ab97)
![Clipboard Image](https://github.com/user-attachments/assets/6549dc1f-f723-47fb-8939-47e9205e3d56)

I guess you may have only checked langauge in app (which is US English in my case) instead of regional format for customizing time chooser control.

**Comment by michalleptuch** [comment]
Poprawka wleci w następnej aktualizacji. Dzięki za zgłoszenie ;)

**Comment by GodlikeRU** [comment]
Dzięki bardzo i pozdrawiam — kozak apka, a MSowi należy się karne wiadomo co za spieprzenie kalendarza w Windows 11 i rozwalenie ich natywnej apki. 👍🏻

**Comment by GodlikeRU** [comment]
Sorry, nie ten przycisk ;)
