### ISSUE TITLE
'Run at startup' setting does not stay on

### ISSUE THREAD

**Issue by PWagner1** [michalleptuch/calendar-flyout#48]
If you toggle the 'Run at startup' switch to 'On', then click a new tab in settings, it will reset itself. Expected behaviour is for the setting to stay on.

**Comment by michalleptuch** [comment]
Hi, thank you for reporting the issue. I can't reproduce your problem. Do you use my app on your private or work computer?

**Comment by PWagner1** [comment]
> Hi, thank you for reporting the issue. I can't reproduce your problem. Do you use my app on your private or work computer?

Hi @michalleptuch 

It's a private computer, the 'bug' has seemed to disappeared now...
