### ISSUE TITLE
Feature Request: Add the ability to show date/time on taskbar

### ISSUE THREAD

**Issue by danialasghar** [michalleptuch/calendar-flyout#5]
It would be great to have the ability to show date and time on the taskbar (with varied configuration options) for users who want to use this app an a complete replacement to the standard clock ... especially ones like who are using explorerpatcher

**Comment by michalleptuch** [comment]
It's very hard to create any custom button that allows you to display date and time on the taskbar. The goal of my app is to deliver functionality of calendar and agenda.
