### ISSUE TITLE
Intermittent activation shortcut issue when bound to Win + C

### ISSUE THREAD

**Issue by stamminator** [michalleptuch/calendar-flyout#51]
I'd like to use `Win + C` as my keyboard shortcut for Calendar Flyout since it's easy for me to remember "<ins>win</ins>dows <ins>c</ins>alendar". When I do, I get intermittent behavior where the start menu will also open when the shortcut is used.

- If there's little-to-no delay in between pressing `Win` and `C`, the issue happens around 3/4 of the time.
- If there's more of a delay in between pressing `Win` and `C`, the issue doesn't happen.
- I haven't been able to reproduce the issue using a different key binding, e.g. `Win + Alt + C`
- If the app's shortcut is disabled, `Win + C` does not open the start menu.

Seems like some sort of race condition to me.

![Animation](https://github.com/user-attachments/assets/592a2ec8-6bb0-4628-a14b-4903dd47812c)

As a workaround attempt, I tried setting the shortcut to `Win + Alt + C` and using PowerToys Keyboard Manager to remap `Win + C` to `Win + Alt + C`, but that didn't pan out.

**Comment by michalleptuch** [comment]
Could you update Calendar Flyout to version 2.1.1 and check if bug still exists?

**Comment by hypedcolee7881** [comment]
I've tried it a few times now and it seems to work perfectly. Thank you for your awesome work!

**Comment by stamminator** [comment]
Works for me too. Thanks!

**Comment by stamminator** [comment]
@michalleptuch Would you mind sharing how you fixed it? I'm getting the same behavior in PowerToys Keyboard Manager when binding `Win + T` to launch an application. I would like to submit a fix, but I don't have much experience in desktop development.
