### ISSUE TITLE
Feature request: ability to open new Outlook instead of Calendar app

### ISSUE THREAD

**Issue by SubjunctiveQuaver** [michalleptuch/calendar-flyout#6]
Hi, not sure how feasible this is, and if data can be pulled directly from the new Outlook app (in preview), but it would be cool if that could be done :)

**Comment by PolarGoose** [comment]
Is it possible to make it work for Office 365 Outlook?

**Comment by michalleptuch** [comment]
It's not in the scope of the nearest update. I need to focus on more notable features.

I tried to connect my app to the new Outlook for Windows app but it's not possible at this moment. I also examined the way to connect my app to Outlook from Office 365 bundle but I didn't enough time for that. I'll back to this case in the future.

**Comment by michalleptuch** [comment]
Calendar Flyout 2.1 will support opening events in Outlook 365 desktop app.

**Comment by AkazaRenn** [comment]
Could we open it in outlook.com in a browser? That could be helpful for those who don't have the heavy-weight Outlook Desktop installed.

**Comment by michalleptuch** [comment]
<img width="307" alt="image" src="https://github.com/michalleptuch/calendar-flyout/assets/43097852/92071bdd-acfb-4388-b3b8-f546dbd80779">

You can do that. Just right-click on event you want and select Open in browser.

**Comment by michalleptuch** [comment]
Calendar Flyout supports opening in classic Outlook app and in browser. I will add support for new Outlook for Windows when it will be available.
